import { NotAFound } from "../Components/404";
import { Component } from "../Components/Componet";
import { Design } from "../Components/Design";
import { Blog } from "../Components/Blog";
import { Development } from "../Components/Developmnt";
// import { Development } from "../Components/Developmnt";
import { Generic } from "./Generic";
import { Recources } from "../Components/Recources";

export let Navbars = [
  {
    id: 1,
    title: "Design",
    path: "design",
    element: <Design />,
    child: [
      {
        id: 10,
        title: "Introduction",
        path: "introduction",
        element: "Introduction",
        text: "Ant Financial has a large number of enterprise-level products. With complex scenarios, designers and developers often need to respond fast due to frequent changes in product demands and concurrent R & D workflow. Many similar contents exist in the process. Through abstraction, we could obtain some stable and highly reusable components and pages.",
      },
      {
        id: 11,
        title: "Design Values",
        path: "designValues",
        element: "Design Values",
        text: "The design values of Ant Design provide designers with internal standards for evaluation, enlighten and inspire the design principles and design patterns, and then offer guidance and general solutions for specific design problems.",
      },
      {
        id: 12,
        title: "Cases",
        path: "cases",
        element: "Cases",
        text: "Starting in April 2015, more and more products of Ant Financial follow Ant Design specification, covering multiple business lines and more than 80 applications. Designed for enterprise-class complex UIs, used by both professional and non-professional designers, Ant Design has a low learning curve that helps you get started fast and achieve rapid results.",
      },
      {
        id: 13,
        title: "Colors",
        path: "colors",
        element: "Colors",
        text: "Ant Design interprets the color system The system-level color system mainly defines the basic color palette, neutral color palette and data visualization color palette in the design of Ant Financial. The product-level color system is in the specific design process, based on the color of the system to further define the tone of the product in accordance with the requirements and function of the color",
      },
      {
        id: 14,
        title: "Layout",
        path: "layout",
        element: "Layout",
        text: "Spatial layout is the starting point of systematic visual design. The difference from traditional graphic design is that the layout space of UI interface should be based on the dynamic and systematic perspective. We were inspired by the architectural ethic of the architect Le Corbusier and explored the dynamic spatial order in UI design and formed the interface layout of Ant Design based on the principle of 'beauty of order', making it possible for designers to create spatial layout that comes with rational beauty.",
      },
      {
        id: 15,
        title: "Font",
        path: "font",
        element: "Font",
        text: "Text is a major channel for users to understand application content and complete their work, and a well designed font system will greatly enhance the user's reading experience and work efficiency. The Ant Design typography system is based on the design principle of  combined with the law of natural logarithm and temperament. We strongly recommend it since it has been verified by a large number of Ant products. While defining the font system for a visual system, we propose to start from the following five aspects:",
      },
      {
        id: 16,
        title: "Icons",
        path: "icons",
        element: "Icons",
        text: "An icon is a graphical representation of meaning. Icons can be used to express actions, state, and even to categorize data. Ant Design's icons adhere to the following two principles and are designed for cross-platform consistency:",
      },
      {
        id: 17,
        title: "Dark Mode",
        path: "darkMode",
        element: "Dark Mode",
        text: "Dark mode is a theme where all UI elements are darkened.",
      },
      {
        id: 18,
        title: "Shadow",
        path: "shadow",
        element: "Shadow",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 19,
        title: "Overview",
        path: "overview",
        element: "Overview",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 21,
        title: "Feedback",
        path: "feedback",
        element: "Feedback",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 22,
        title: "Navigation",
        path: "navigation",
        element: "Navigation",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
    ],
  },
  {
    id: 2,
    title: "Development",
    path: "development",
    element: <Development />,
    child: [
      {
        id: 23,
        title: "Ant Design of React",
        path: "antDesignOfReact",
        element: "Ant Design of React",
        text: "Ant Financial has a large number of enterprise-level products. With complex scenarios, designers and developers often need to respond fast due to frequent changes in product demands and concurrent R & D workflow. Many similar contents exist in the process. Through abstraction, we could obtain some stable and highly reusable components and pages.",
      },
      {
        id: 24,
        title: "Getting Started",
        path: "gettingStarted",
        element: "Getting Started",
        text: "The design values of Ant Design provide designers with internal standards for evaluation, enlighten and inspire the design principles and design patterns, and then offer guidance and general solutions for specific design problems.",
      },
      {
        id: 25,
        title: "Real Project With Umi",
        path: "realProject",
        element: "Real project With Umi",
        text: "Starting in April 2015, more and more products of Ant Financial follow Ant Design specification, covering multiple business lines and more than 80 applications. Designed for enterprise-class complex UIs, used by both professional and non-professional designers, Ant Design has a low learning curve that helps you get started fast and achieve rapid results.",
      },
      {
        id: 26,
        title: "Use in create-react-app",
        path: "usecreate-react-app",
        element: "Use in create-react-app",
        text: "Ant Design interprets the color system The system-level color system mainly defines the basic color palette, neutral color palette and data visualization color palette in the design of Ant Financial. The product-level color system is in the specific design process, based on the color of the system to further define the tone of the product in accordance with the requirements and function of the color",
      },
      {
        id: 27,
        title: "Use in Typescript",
        path: "useinTypyscript",
        element: "Use in Typescript",
        text: "Spatial layout is the starting point of systematic visual design. The difference from traditional graphic design is that the layout space of UI interface should be based on the dynamic and systematic perspective. We were inspired by the architectural ethic of the architect Le Corbusier and explored the dynamic spatial order in UI design and formed the interface layout of Ant Design based on the principle of 'beauty of order', making it possible for designers to create spatial layout that comes with rational beauty.",
      },
      {
        id: 28,
        title: "Css Competable",
        path: "cssCompetable",
        element: "Css Competable",
        text: "Text is a major channel for users to understand application content and complete their work, and a well designed font system will greatly enhance the user's reading experience and work efficiency. The Ant Design typography system is based on the design principle of  combined with the law of natural logarithm and temperament. We strongly recommend it since it has been verified by a large number of Ant products. While defining the font system for a visual system, we propose to start from the following five aspects:",
      },
      {
        id: 29,
        title: "Customes Theme",
        path: "customesTheme",
        element: "Customes Theme",
        text: "An icon is a graphical representation of meaning. Icons can be used to express actions, state, and even to categorize data. Ant Design's icons adhere to the following two principles and are designed for cross-platform consistency:",
      },
      {
        id: 30,
        title: "Use Costumise",
        path: "useCostimise",
        element: "Use Costumise",
        text: "Dark mode is a theme where all UI elements are darkened.",
      },
      {
        id: 31,
        title: "v4 to v5",
        path: "v4tov5",
        element: "v4 to v5",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 32,
        title: "Third-party Libraries",
        path: "third-party-libraries",
        element: "Third-party Libraries",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 33,
        title: "Internationazational",
        path: "internationazational",
        element: "Internationazational",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 34,
        title: "FAQ",
        path: "faq",
        element: "FAQ",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
    ],
  },
  {
    id: 3,
    title: "Components",
    path: "components",
    element: <Component />,
    child: [
      {
        id: 36,
        title: "Components overview",
        path: "componentsoverview",
        element: "Components overview",
        text: "Ant Financial has a large number of enterprise-level products. With complex scenarios, designers and developers often need to respond fast due to frequent changes in product demands and concurrent R & D workflow. Many similar contents exist in the process. Through abstraction, we could obtain some stable and highly reusable components and pages.",
      },
      {
        id: 37,
        title: "Button",
        path: "button",
        element: "Button",
        text: "The design values of Ant Design provide designers with internal standards for evaluation, enlighten and inspire the design principles and design patterns, and then offer guidance and general solutions for specific design problems.",
      },
      {
        id: 38,
        title: "Icon",
        path: "icon",
        element: "Icon",
        text: "Starting in April 2015, more and more products of Ant Financial follow Ant Design specification, covering multiple business lines and more than 80 applications. Designed for enterprise-class complex UIs, used by both professional and non-professional designers, Ant Design has a low learning curve that helps you get started fast and achieve rapid results.",
      },
      {
        id: 39,
        title: "Typography",
        path: "typography",
        element: "Typography",
        text: "Ant Design interprets the color system The system-level color system mainly defines the basic color palette, neutral color palette and data visualization color palette in the design of Ant Financial. The product-level color system is in the specific design process, based on the color of the system to further define the tone of the product in accordance with the requirements and function of the color",
      },
      {
        id: 40,
        title: "Devider",
        path: "devider",
        element: "Devedir",
        text: "Spatial layout is the starting point of systematic visual design. The difference from traditional graphic design is that the layout space of UI interface should be based on the dynamic and systematic perspective. We were inspired by the architectural ethic of the architect Le Corbusier and explored the dynamic spatial order in UI design and formed the interface layout of Ant Design based on the principle of 'beauty of order', making it possible for designers to create spatial layout that comes with rational beauty.",
      },
      {
        id: 41,
        title: "Grid",
        path: "grid",
        element: "Grid",
        text: "Text is a major channel for users to understand application content and complete their work, and a well designed font system will greatly enhance the user's reading experience and work efficiency. The Ant Design typography system is based on the design principle of  combined with the law of natural logarithm and temperament. We strongly recommend it since it has been verified by a large number of Ant products. While defining the font system for a visual system, we propose to start from the following five aspects:",
      },
      {
        id: 42,
        title: "Space",
        path: "space",
        element: "Space",
        text: "An icon is a graphical representation of meaning. Icons can be used to express actions, state, and even to categorize data. Ant Design's icons adhere to the following two principles and are designed for cross-platform consistency:",
      },
      {
        id: 43,
        title: "Anchor",
        path: "anchor",
        element: "Anchor",
        text: "Dark mode is a theme where all UI elements are darkened.",
      },
      {
        id: 44,
        title: "BreadCrumb",
        path: "breadCrumb",
        element: "BreadCrumb",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 45,
        title: "Navbar",
        path: "navbar",
        element: "Navbar",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 46,
        title: "Menu",
        path: "menu",
        element: "menu",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 47,
        title: "Pagination",
        path: "pagination",
        element: "Pagination",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
    ],
  },
  {
    id: 4,
    title: "Blog",
    path: "blog",
    element: <Blog />,
    child: [
      {
        id: 48,
        title: "Unnecessary Rerender",
        path: "unnecaryRerender",
        element: "Unnecessary Rerender",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 49,
        title: "Funny Modal hook BUG",
        path: "funnyModalHookBug",
        element: "Funny Modal hook BUG",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 50,
        title: "About Antd test library ",
        path: "aboutAntdTestLibraryMigration",
        element: "About Antd test library ",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 51,
        title: "Tree's check conduction",
        path: "treesCheckConduction",
        element: "Tree's check conduction",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 52,
        title: "How to Grow as a Collaboator",
        path: "howtoGrowasaCollaboator",
        element: "How to Grow as a Collaboator",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 53,
        title: "Some change on getContainer",
        path: "someChangeonGetContainer",
        element: "Some change on getContainer",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
      {
        id: 54,
        title: "Component-level Css-in-Js",
        path: "Component-levelCssinJS",
        element: "Component-level Css-in-Js",
        text: "The use of design patterns in enterprise-level businesses can significantly increase the certainty of the R&D team, save unnecessary design and maintain system consistency, allowing designers to focus on creativity where it is most needed.",
      },
    ],
  },
  {
    id: 5,
    title: "Recources",
    path: "recources",
    element: <Recources />,
  },
];
